name: Test

on: 
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go-versions: [1.12.x, 1.13.x, 1.14.x]
        platforms: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matric.go-version }}

      - uses: actions/checkout@v2
        run: go test ./...